name: Build RP2040

on:
  workflow_call:
    inputs:
      board:
        required: true
        type: string

env:
  PLATFORMIO_CACHE_DIR: ~/.platformio
  BUILD_RETENTION_DAYS: 30

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
            ~/.cache/pip
          key: ${{ runner.os }}-pio-rp2040-${{ inputs.board }}-${{ hashFiles('**/platformio.ini', '**/boards/*.json') }}
          restore-keys: |
            ${{ runner.os }}-pio-rp2040-${{ inputs.board }}-
            ${{ runner.os }}-pio-rp2040-
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Check RP2040 platform version
        run: platformio platform show raspberrypi

      - name: Build firmware
        run: |
          platformio run -e ${{ inputs.board }}
          mkdir -p artifacts
          # Copy UF2 files (primary firmware format for RP2040)
          cp .pio/build/${{ inputs.board }}/*.uf2 artifacts/ || true
          # Copy ELF for debugging
          cp .pio/build/${{ inputs.board }}/*.elf artifacts/ || true
          # Copy BIN files if they exist
          cp .pio/build/${{ inputs.board }}/*.bin artifacts/ || true
          # Copy littlefs image if it exists
          cp .pio/build/${{ inputs.board }}/littlefs*.bin artifacts/ || true

      - name: Analyze firmware size
        run: |
          echo "Firmware size analysis for ${{ inputs.board }}"
          platformio run --target size -e ${{ inputs.board }}
          echo "Memory usage details:"
          python -c "
          import os
          import glob
          
          def format_size(size, total=None):
              if total:
                  return f'{size:,} bytes ({size/total*100:.1f}%)'
              return f'{size:,} bytes'
          
          # RP2040 specs
          FLASH_SIZE = 2 * 1024 * 1024  # 2MB (most common)
          RAM_SIZE = 264 * 1024         # 264KB (SRAM + SCRATCH_X/Y)
          
          elf_files = glob.glob('.pio/build/${{ inputs.board }}/*.elf')
          if elf_files:
              elf_size = os.path.getsize(elf_files[0])
              print(f'ELF size: {format_size(elf_size)}')
          
          uf2_files = glob.glob('.pio/build/${{ inputs.board }}/*.uf2')
          for f in uf2_files:
              size = os.path.getsize(f)
              print(f'{os.path.basename(f)}: {format_size(size)} (Flash usage: {format_size(size/2, FLASH_SIZE)})')
          
          bin_files = glob.glob('.pio/build/${{ inputs.board }}/*.bin')
          for f in bin_files:
              size = os.path.getsize(f)
              print(f'{os.path.basename(f)}: {format_size(size)}')
          "

      - name: Get version info
        id: version
        run: echo "long=$(./bin/buildinfo.py long)" >> $GITHUB_OUTPUT

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-rp2040-${{ inputs.board }}-${{ steps.version.outputs.long }}
          path: artifacts/
          retention-days: ${{ env.BUILD_RETENTION_DAYS }}
          if-no-files-found: error

      - name: Upload build report
        uses: actions/upload-artifact@v4
        with:
          name: build-report-rp2040-${{ inputs.board }}-${{ steps.version.outputs.long }}
          path: |
            .pio/build/${{ inputs.board }}/*.map
            .pio/build/${{ inputs.board }}/compile_commands.json
            .pio/build/${{ inputs.board }}/generated
          retention-days: ${{ env.BUILD_RETENTION_DAYS }}
          if-no-files-found: warn
